{% set version = "1.0.0" %}
{% set checksum = "864209f54934bc8de064c4be403f8e49d532574334ae6bce76d193659866a87d" %}

package:
  name: z5py
  version: {{ version }}

source:
    url: https://github.com/constantinpape/z5/archive/{{ version }}.tar.gz
    sha256: {{ checksum }}

build:
  number: 2
  skip: True  # [win and vc<14]

requirements:
  build:
    - python {{ python }}
    - boost {{ boost }}
    - numpy {{ numpy }}
    - xtensor >=0.17.1,<0.18
    - xtensor-python >=0.20,<0.21
    - blosc
    - bzip2
    - xz
    - zlib {{ zlib }}
    - nlohmann_json
  run:
    - python
    - boost
    - numpy
    - blosc
    - bzip2
    - xz
    - zlib
    - six
    - futures  # [py27]

test:
  imports:
    - z5py
  source_files:
    - src/python/test/*.py
  commands:
    - python -m unittest discover -s src/python/test -v

about:
  home: https://github.com/constantinpape/z5
  license: MIT
  license_file: LICENSE
  summary: Lightweight C++ and Python interface for datasets in zarr and N5 format.

extra:
  recipe-maintainers:
    - constantinpape
